# NumPy library

### Data types and attributes

In [1]:
import numpy as np

In [4]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [5]:
type(a1)

numpy.ndarray

In [12]:
a3 = np.array([[[1, 2.5, 3.3], 
                [1 , 5.7, 9.6], 
                [5, 7 ,8.9]],
               
                [[10, 6, 8],
                [3, 7 ,8],
                [9, 9.8, 7]]])
a3

array([[[ 1. ,  2.5,  3.3],
        [ 1. ,  5.7,  9.6],
        [ 5. ,  7. ,  8.9]],

       [[10. ,  6. ,  8. ],
        [ 3. ,  7. ,  8. ],
        [ 9. ,  9.8,  7. ]]])

In [13]:
a3. shape

(2, 3, 3)

In [14]:
a3.ndim

3

In [15]:
a3.dtype

dtype('float64')

In [16]:
a3.size

18

In [17]:
a3

array([[[ 1. ,  2.5,  3.3],
        [ 1. ,  5.7,  9.6],
        [ 5. ,  7. ,  8.9]],

       [[10. ,  6. ,  8. ],
        [ 3. ,  7. ,  8. ],
        [ 9. ,  9.8,  7. ]]])

In [18]:
type(a3)

numpy.ndarray

### Create a dataFrame from a numpy array

In [22]:
a2= np.array(  [ [1, 5, 7],
               [3, 7, 9]])
a2

array([[1, 5, 7],
       [3, 7, 9]])

In [23]:
import pandas as pd

df= pd.DataFrame(a2)
df

0  1  2
0  1  5  7
1  3  7  9

## Creating arrays

In [24]:
sample_array = np. array ([1, 2, 3])
sample_array

array([1, 2, 3])

In [25]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
random_array= np.random.randint(0, 10, size=(3,5))

In [28]:
random_array

array([[5, 3, 1, 4, 6],
       [0, 9, 1, 2, 5],
       [3, 8, 6, 5, 5]])

In [29]:
random_array.size

15